import type { Metadata } from "next";
import { Bungee } from "next/font/google";
import "./globals.css";

const inter = Bungee({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#090029] text-white`}>
        {children}
      </body>
    </html>
  );
}
